

window.ftc = window.ftc || {}, ftc.ManagerLan = {
    ZH: "zh",
    TR: "tr",
    EN: "en",
    JA: "ja",
    KO: "ko",
    curLang: "zh",
    lang: {},
    init: function (e) {
        if (e || (e = this.ZH), this.lang[e] || (cc.log("警告：未找到语言" + e), e = this.ZH), this.lang[e] ? this._lanFile = t(e) : this._lanFile = {}, this.curLang = e, !this.isZH()) {
            var i = 0;
            switch (e) {
                case this.EN:
                    i = 1;
                    break;
                case this.JA:
                    i = 2;
                    break;
                case this.KO:
                    i = 3
            }
            for (var a in this._sysLang) this._sysLang[a] = this._sysLang[a][i]
        }
    },
    getLanguage: function () {
        return this.curLang
    },
    t: function (t, e) {
        var i = this._lanFile[t];
        if (void 0 === i && (this.isZH() || (i = this._sysLang[t]), void 0 === i && (i = t)), e)
            for (var a in e) i = i.replace("%{" + a + "}", e[a]);
        return i
    },
    isZH: function () {
        return this.getLanguage() == this.ZH
    },
    _sysLang: {
        "再按一次退出游戏": ["再按一次退出遊戲", "Press again to exit the game", "次回押すとゲーム終了", ""],
        "支付失败": ["支付失敗", "Payment failed", "支払い失敗", ""],
        "支付取消": ["支付取消", "Payment cancellation", "支払い中止", ""],
        "获取订单成功...": ["獲取訂單成功…", "Get order successfully", "注文情報獲得成功…", ""],
        "分享成功": ["分享成功", "Share success", "シェア成功", ""],
        "分享失败": ["分享失敗", "Failed to share", "シェア失敗", ""],
        "分享取消": ["分享取消", "Share cancellation", "シェア中止", ""],
        "观看取消": ["觀看取消", "Watch cancel", "鑑賞中止", ""],
        "不支持打开网址": ["不支持打開網址", "Opening web address is not supported", "請求するURLが支持されません", ""],
        "正在重新启动游戏...": ["正在重新啟動遊戲…", "Restarting game", "ゲーム再起動中…", ""],
        "正在重连...": ["正在重連…", "Reconnecting", "再接続中…", ""],
        "测试版本无法进行充值": ["測試版本無法進行充值", "The test version cannot be recharged", "テスト版ではチャージできません", ""],
        "获取订单中...": ["獲取訂單中…", "Get order", "注文情報獲得中…", ""],
        "等待充值完成...": ["等待充值完成…", "Waiting for recharge to complete", "決算中…", ""],
        "联系客服": ["聯系客服", "Contact customer service", "問い合わせ", ""],
        "请重新进入": ["請重新進入", "Please re-enter", "もう一度お試しください", ""],
        "网络错误": ["網絡錯誤", "network error", "ネットワークエラー", ""],
        "正在检查账号...": ["正在檢查帳號…", "Checking account number", "アカウントチェック中…", ""],
        "创建": ["創建", "establish", "新規", ""],
        "前往登录": ["前往登入", "Go to login", "ログインへ", ""],
        "登录": ["登入", "Sign in", "ログイン", ""],
        "前往注册": ["前往注册", "Go to register", "登録へ", ""],
        "设置": ["設定", "set up", "設置", ""],
        "设置账号": ["設定帳號", "Set account number", "アカウント設置", ""],
        "账号绑定错误": ["帳號綁定錯誤", "Account binding error", "アカウント連携エラー", ""],
        "获取数据中...": ["獲取數據中…", "Get data in", "データ読み込み中…", ""],
        "注册成功": ["注册成功", "login was successful", "登録成功", ""],
        "登录成功": ["登入成功", "Login successful", "ログイン成功", ""],
        "账号设置成功": ["帳號設定成功", "Account set successfully", "アカウント設置成功", ""],
        "账号修改成功": ["帳號修改成功", "Account modified successfully", "アカウント変更成功", ""],
        "账号不能为空": ["帳號不能為空", "Account number cannot be empty", "アカウントまたはパスワードは空にできません", ""],
        "密码不能为空": ["密碼不能為空", "Password cannot be empty", "ログイン操作は現在データを空にする。続く？", ""],
        "登录账号会清除当前的数据，是否继续?": ["登入帳號會清除當前的數據，是否繼續？", "Login account will clear current data. Do you want to continue?", "ログイン中…", ""],
        "登录中...": ["登入中…", "Logging in", "アカウントは空にできません", ""],
        "账号不得为空": ["帳號不得為空", "Account number cannot be empty", "アカウントはせめて3文字以上", ""],
        "账号不得小于3位": ["帳號不得小於3比特", "The account number must not be less than 3 digits", "アカウントは最大18文字", ""],
        "账号不得大于18位": ["帳號不得大於18比特", "The account number should not be greater than 18 digits", "特殊文字が含めている", ""],
        "账号不能包含特殊字符": ["帳號不能包含特殊字元", "Account number cannot contain special characters", "設置中…", ""],
        "设置中...": ["設定中…", "Setting", "パスワードはせめて6文字以上", ""],
        "密码不得小于6位": ["密碼不得小於6比特", "The password must not be less than 6 digits", "パスワードは最大18文字", ""],
        "密码不得大于18位": ["密碼不得大於18比特", "The password should not be greater than 18 digits", "登録中…", ""],
        "注册中...": ["注册中…", "Registering", "コメントは空にできません", ""],
        "评论内容不能为空": ["評論內容不能為空", "Comment content cannot be empty", "コメント成功", ""],
        "评论成功": ["評論成功", "Comment successful", "コメント失敗", ""],
        "评论失败": ["評論失敗", "Comment failed", "JSON\u89e3\u6790\u30a8\u30e9\u30fc", ""],
        "json\u89e3\u6790\u51fa\u9519": ["json\u89e3\u6790\u51fa\u932f", "JSON parsing error", "較正エラー", ""],
        "校验出错": ["校驗出錯", "Verification error", "重複したパッケージが受信されます", ""],
        "收到重复的数据包": ["收到重複的數据包", "Duplicate packet received", "ダウンロードエラー", ""],
        "下载出错": ["下載出錯", "Download error", "接続エラー", ""],
        "连接出错": ["連接出錯", "link error ", "サーバーに接続できません", ""],
        "无法连接服务器": ["無法連接服務器", "Unable to connect to the server", "バックグラウンドのリアルタイムデータを取得する（開発専用）", ""],
        "获得后台实时数据（开发专用）": ["獲得後臺即時資料（開發專用）", "Get background real-time data (for development only)", "クライアントバージョンが不一致", ""],
        "客户端版本不匹配！": ["用戶端版本不匹配！", "Client version mismatch!", "ネットワーク停止", ""],
        "网络中断": ["網絡中斷", "Network disruption", "接続がタイムアウト", ""],
        "连接超时": ["連接超時", "connection timed out", "ネットワーク異常", ""],
        "网络异常": ["網絡异常", "Network anomaly", "チャージ結果の表示が遅延かもしれません。再ログインください。", ""],
        "充值到账可能存在延迟，请尝试重新进入游戏": ["充值到賬可能存在延遲，請嘗試重新進入遊戲", "Recharge to the account may be delayed, please try to re-enter the game", "サーバーとの接続が失われました。ゲームを再起動してください。", ""],
        "已经与服务器失去联系，请重新开始游戏": ["已經與服務器失去聯繫，請重新開始遊戲", "You have lost contact with the server. Please restart the game", "ホットアップデートバージョンが不一致！！！", ""],
        "热更新版本不匹配!!!": ["熱更新版本不匹配！！！", "Hot update version does not match!!!", "ネットワーク環境不安定のため、リソースの読み込みエラーが発生。再ログインください！", ""],
        "网络不稳定，资源加载出错，请重新进入游戏！": ["網絡不穩定，資源加載出錯，請重新進入遊戲！", "Network instability, resource loading error, please re-enter the game!", "注文失敗。お問い合わせまたは再ログインください。", ""],
        "订单失败,可以联系我们的客服或尝试重新登录游戏": ["訂單失敗，可以聯繫我們的客服或嘗試重新登入遊戲", "If the order fails, you can contact our customer service or try to login the game again", "データ更新成功。再ログインください。", ""],
        "新数据下载成功，请重新进入游戏": ["新數據下載成功，請重新進入遊戲", "New data downloaded successfully, please re-enter the game", "データ更新失敗。再ログインください。", ""],
        "新数据下载失败，请重新进入游戏": ["新數據下載失敗，請重新進入遊戲", "New data download failed, please re-enter the game", "最新バージョンをインストールください。", ""],
        "请安装最新包": ["請安裝最新包", "Please install the latest package", "最新バージョンをダウンロードしますか？", ""],
        "是否下载最新版本?": ["是否下載最新版本？", "Do you want to download the latest version?", "是否需要登录账号:%{name}，登录后当前数据将被清除，是否继续？", ""],
        "是否需要登录账号:%{name}，登录后当前数据将被清除，是否继续？": ["是否需要登入帳號：%{name}，登入後當前數據將被清除，是否繼續？", "Do you need to log in account:% {name}, the current data will be cleared after login, do you want to continue?", "申し訳ありません、プログラムがエラーになりました！", ""],
        "很抱歉，程序不小心出错了!": ["很抱歉，程式不小心出錯了！", "I'm sorry, the program went wrong!", "【戻る】で画面を閉じます", ""],
        "【返回键】关闭界面": ["【返回鍵】關閉介面", "[return] to close the interface", "パッケージダウンロード中:%{name}%", ""],
        "下载安装包进度:%{name}%": ["下載安裝包進度：%{name}%", "Download installation package progress:% {name}%", "本画面が%{name}秒後閉じます", ""],
        "本窗口在%{name}秒后关闭": ["本視窗在%{name}秒後關閉", "This window closes in% {name} seconds", "パッケージダウンロード中%{name1}MB/%{name2}MB", ""],
        "下载安装包%{name1}MB/%{name2}MB": ["下載安裝包%{name1}MB/%{name2}MB", "Download installation package% {name1} MB /% {Name2} MB", "%{name}\u5143\u5b9d\u8cfc\u5165", ""],
        "购买%{name}元宝": ["購買%{name}元寶", "Buy% {name} Yuanbao", "%{name}\u5143\u5b9d\u8d08\u308b", ""],
        "赠送%{name}元宝": ["贈送%{name}元寶", "Present% {name} Yuanbao", "元", ""],
        "元": ["元", "element", "注文確認中", ""],
        "正在检查订单": ["正在檢查訂單", "Checking orders", "一覧戻る", ""],
        "返回列表": ["返回列表", "Back to list", "スイープコードでお問い合わせ", ""],
        "手机扫码进入在线客服系统": ["手機掃碼進入線上客服系統", "Mobile phone scanning code into online customer service system", "携帯電話のスキャンコードはオンラインサービスシステムに入ります。", ""],
        "新增项": ["新增項", "New items", "新規アイテム", ""],
        "昵称未设置": ["昵稱未設定", "Nickname not set", "ニックネームが設定されていません", ""],
        "等级:": ["等級：", "Grade:", "レベル:", ""],
        "周目:": ["周目：", "Zhou Mu:", "週:", ""],
        "战力:": ["戰力：", "Combat power:", "戦力:", ""],
        "任务:": ["任務：", "Task:", "タスク:", ""],
        "小时后删除:": ["小時後删除：", "Delete after hours:", "時間後に削除:", ""],
        "进入游戏": ["進入遊戲", "Enter the game", "ゲームに入る", ""],
        "切换游戏": ["切換遊戲", "Switch games", "ゲームを切り替え", ""],
        "点击切换存档": ["點擊切換存檔", "Click to switch to archive", "クリックしてアーカイブを切り替えます", ""],
        "点击升级账号": ["點擊陞級帳號", "Click upgrade account", "アップグレードアカウントをクリックします", ""],
        "请先同意《用户使用许可协议》和《用户隐私协议》": ["請先同意《用戶使用許可協議》和《用戶隱私協議》", "Please agree to the user license agreement and user privacy agreement first", "まず「ユーザ使用許諾協議」と「ユーザプライバシー協議」に同意してください。", ""],
        "正在加载数据...": ["正在加載數據…", "Loading data", "データをロード中..。", ""],
        "确认新建存档并开始游戏吗?": ["確認新建存檔並開始遊戲嗎？", "Are you sure to create a new archive and start the game?", "新しいアーカイブを確認してゲームを開始しますか？", ""],
        "正在保存数据中...": ["正在保存數據中…", "Saving data", "データを保存中..。", ""],
        "删除存档需要等待3天，是否继续删除此存档？": ["删除存檔需要等待3天，是否繼續删除此存檔？", "It takes 3 days to delete the archive. Do you want to continue to delete this archive?", "アーカイブを削除するには3日間待つ必要がありますが、このアーカイブを引き続き削除しますか？", ""],
        "正在提交删除请求...": ["正在提交删除請求…", "Submitting delete request", "削除要求を送信中..。", ""],
        "确定要撤销删除么，撤销删除后可立即恢复存档？": ["確定要撤銷删除麼，撤銷删除後可立即恢復存檔？", "Are you sure you want to undo the deletion? You can restore the archive immediately after canceling the deletion?", "削除をキャンセルしますか？削除したらすぐにアーカイブを復元できますか？", ""],
        "正在提交撤消请求...": ["正在提交撤銷請求…", "Submitting undo request", "キャンセル要求を送信しています。", ""],
        "账号密码不能为空": ["帳號密碼不能為空", "Account password cannot be empty", "アカウントのパスワードが空です。", ""],
        "修改账号": ["修改帳號", "Account modification", "アカウントを変更", ""],
        "请输入3-18位新账号": ["請輸入3-18比特新帳號", "Please input 3-18 digit new account", "3-18\u6841\u306e\u65b0\u3057\u3044\u30a2\u30ab\u30a6\u30f3\u30c8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002", ""],
        "设置账号密码": ["設定帳號密碼", "Set account password", "アカウントのパスワードを設定", ""],
        "请输入6-18位新密码": ["請輸入6-18比特新密碼", "Please enter a new password of 6-18 digits", "6-18\u6841\u306e\u65b0\u3057\u3044\u30d1\u30b9\u30ef\u30fc\u30c9\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002", ""],
        "重置密码": ["重置密碼", "reset password ", "パスワードをリセット", ""],
        "请再次输入密码": ["請再次輸入密碼", "Please enter the password again", "パスワードをもう一度入力してください。", ""],
        "操作成功": ["操作成功", "The operation was successful", "操作が成功しました", ""],
        "请先登录": ["請先登錄", "Please log in first", "まず登録してください", ""],
        "两次输入密码不一致": ["兩次輸入密碼不一致", "The two passwords are inconsistent", "二回の入力パスワードが一致しません。", ""],
        "密码重置后，已登录此账号的设备将会失效，是否继续？": ["密碼重置後，已登入此帳號的設備將會失效，是否繼續？", "After the password is reset, the device logged in to this account will be invalid. Do you want to continue?", "パスワードがリセットされたら、このアカウントに登録されたデバイスは無効になります。続けますか？", ""],
        "重置中...": ["重置中…", "Resetting", "リセット中..", ""],
        "升级中...": ["陞級中…", "Upgrading", "アップグレード中…", ""],
        "请输入手机号": ["請輸入手機號", "Please enter your mobile phone number", "携帯の番号を入力してください", ""],
        "请使用已绑定的手机号登录": ["請使用已綁定的手機號登入", "Please log in with the bound mobile number", "バインディングされた携帯電話番号で登録してください。", ""],
        "手机号登录": ["手機號登入", "Mobile phone number login", "携帯番号の登録", ""],
        "升级为手机账户，可以提高账户安全": ["陞級為手機帳戶，可以提高帳戶安全", "Upgrade to mobile account, can improve account security", "携帯口座にアップグレードすれば、口座の安全が向上します。", ""],
        "绑定手机号": ["綁定手機號", "Bind mobile phone number", "携帯番号を結びつける", ""],
        "请使用已绑定的手机号验证": ["請使用已綁定的手機號驗證", "Please use the bound mobile phone number for verification", "バインディングされた携帯電話番号で確認してください。", ""],
        "手机号验证": ["手機號驗證", "Mobile phone number verification", "携帯番号の検証", ""],
        "请输入邮箱账号": ["請輸入郵箱帳號", "Please input email account", "メールアドレスを入力してください。", ""],
        "请使用已绑定的邮箱账号登录": ["請使用已綁定的郵箱帳號登入", "Please log in with the bound email account", "バインディングされたメールアカウントを使って登録してください。", ""],
        "邮箱登录": ["郵箱登錄", "Email login", "メールアドレス", ""],
        "升级为邮箱账户，可以提高账户安全": ["陞級為郵箱帳戶，可以提高帳戶安全", "Upgrade to email account, can improve account security", "メールアカウントにアップグレードすると、アカウントのセキュリティが向上します。", ""],
        "绑定邮箱": ["綁定郵箱", "Bind mailbox", "メールボックスをバインド", ""],
        "请使用已绑定的邮箱账号验证": ["請使用已綁定的郵箱帳號驗證", "Please use the bound email account for verification", "バインディングされたメールアドレスを使って確認してください。", ""],
        "邮箱验证": ["郵箱驗證", "Mailbox verification", "メール認証", ""],
        "下一步": ["下一步", "next step", "次のステップ", ""],
        "获取验证码": ["獲取驗證碼", "Get captcha", "認証コードを取得", ""],
        "秒后重新获取": ["秒後重新獲取", "Seconds later", "秒後に再取得します", ""],
        "登录账号出错，请重试": ["登入帳號出錯，請重試", "Login account error, please try again", "アカウントの登録エラーが発生しました。やり直してください。", ""],
        "绑定账号出错，请重试": ["綁定帳號出錯，請重試", "Error binding account, please try again", "アカウントのバインドエラーが発生しました。やり直してください。", ""],
        "验证码发送成功": ["驗證碼發送成功", "Verification code sent successfully", "認証コードの送信に成功しました。", ""],
        "请输入正确的手机号码": ["請輸入正確的手機號碼", "Please enter the correct mobile phone number", "正しい携帯電話番号を入力してください。", ""],
        "请输入正确的邮箱地址": ["請輸入正確的郵箱地址", "Please enter the correct email address", "正しいメールアドレスを入力してください。", ""],
        "请输入正确的验证码": ["請輸入正確的驗證碼", "Please enter the correct verification code", "正しい検証コードを入力してください。", ""],
        "正在登录...": ["正在登入…", "Signing in", "ログイン中..", ""],
        "正在绑定...": ["正在綁定…", "Binding", "バインド中..", ""],
        "正在创建并绑定...": ["正在創建並綁定…", "Creating and binding", "作成およびバインディング..。", ""],
        "该邮箱未绑定，是否将当前存档绑定至该邮箱？": ["該郵箱未綁定，是否將當前存檔綁定至該郵箱？", "The mailbox is not bound. Do you want to bind the current archive to this mailbox?", "このメールボックスはバインドされていません。現在のアーカイブをメールボックスにバインドしますか？", ""],
        "该手机号未绑定，是否将当前存档绑定至该手机号？": ["該手機號未綁定，是否將當前存檔綁定至該手機號？", "The mobile phone number is not bound. Do you want to bind the current archive to the mobile phone number?", "この携帯番号はバインディングされていません。現在のアーカイブをこの携帯番号に結びつけますか？", ""],
        "该邮箱已绑定其他账号，如果继续操作已绑定账号将自动解绑，是否继续？": ["該郵箱已綁定其他帳號，如果繼續操作已綁定帳號將自動解綁，是否繼續？", "This mailbox has been bound with other accounts. If you continue, the bound account will be unbound automatically. Do you want to continue?", "このメールボックスは他のアカウントと接続されています。接続されたアカウントを操作し続けると自動的に解除されます。続けますか？", ""],
        "该手机号已绑定其他账号，如果继续操作已绑定账号将自动解绑，是否继续？": ["該手機號已綁定其他帳號，如果繼續操作已綁定帳號將自動解綁，是否繼續？", "The mobile phone number has been bound to other accounts. If you continue, the bound account will be automatically unbound. Do you want to continue?", "この携帯番号は他のアカウントに接続されています。接続されたアカウントを操作し続けると自動的に解除されます。続けますか？", ""],
        "该邮箱已绑定其他账号，不能再次绑定": ["該郵箱已綁定其他帳號，不能再次綁定", "The mailbox has been bound with other accounts, so it cannot be bound again", "このメールボックスは他のアカウントにバインドされていますので、もう一回バインドすることはできません。", ""],
        "该手机号已绑定其他账号，不能再次绑定": ["該手機號已綁定其他帳號，不能再次綁定", "The mobile phone number has been bound to other accounts. It cannot be bound again", "この携帯番号は他のアカウントと紐付けされていますので、再度紐付けすることはできません。", ""],
        "正在确认验证码...": ["正在確認驗證碼…", "Confirming captcha", "検証コードを確認していますが…", ""],
        "切换账号": ["切換帳號", "Switch account", "アカウントを切り替え", ""],
        "建议尽快绑定账户，以防数据丢失": ["建議儘快綁定帳戶，以防資料丟失", "It is recommended to bind the account as soon as possible to prevent data loss", "データの紛失を防ぐために、できるだけ早く口座を縛ってください。", ""],
        "游客": ["遊客", "tourist", "観光客", ""],
        "登录账号": ["登入帳號", "Login account", "ログインID", ""],
        "建议尽快创建账户，以防数据丢失": ["建議儘快創建帳戶，以防資料丟失", "It is recommended to create an account as soon as possible to prevent data loss", "データの紛失を防ぐために、できるだけ早く口座を作ってください。", ""],
        "你已实名认证": ["你已實名認證", "You have been certified by your real name", "あなたは実名認証済みです", ""],
        "前往实名认证": ["前往實名認證", "Go to real name authentication", "実名認証に行く", ""],
        "已绑定手机号": ["已綁定手機號", "Bound mobile phone number", "バインドされた携帯番号", ""],
        "已绑定邮箱": ["已綁定郵箱", "Bound mailbox", "バインドされたメールボックス", ""],
        "查看引继码": ["查看引繼碼", "View reference code", "参照コード", ""],
        "创建引继码": ["創建引繼碼", "Create a reference code", "リードコードを作成", ""],
        "已绑定微信": ["已綁定微信", "Bound wechat", "バインドされたマイクロメッセージ", ""],
        "绑定微信": ["綁定微信", "Binding wechat", "ウィーチャットを結合する", ""],
        "账号只能修改一次，是否立即前往修改？": ["帳號只能修改一次，是否立即前往修改？", "The account can only be modified once. Do you want to modify it now?", "アカウントは一回だけ変更できますが、すぐに変更に行きますか？", ""],
        "你已绑定手机号": ["你已綁定手機號", "You have bound your mobile phone number", "あなたは携帯番号をバインドしました。", ""],
        "你已绑定邮箱": ["你已綁定郵箱", "You have bound your email address", "メールボックスをバインドしました", ""],
        "你已绑定微信": ["你已綁定微信", "You have bound wechat", "あなたは既にWeChatをバインドしています", ""],
        "无法进入用户中心，请确保网络连通": ["無法進入用戶中心，請確保網絡連通", "Unable to enter user center, please make sure the network is connected", "ユーザーセンターに入れませんでした。ネットワーク接続を確保してください。", ""]
    },
    toolSaveSysLangKeys2File: function () {
        var t = "";
        for (var e in this._sysLang) t += e + "\n";
        jsb.fileUtils.writeStringToFile(t, "lang/zh.txt")
    },
    toolLoadSysLangFromFile: function () {
        var t = ft.replaceAll(jsb.fileUtils.getStringFromFile("lang/zh.txt"), "\r\n", "\n"),
            e = ft.replaceAll(jsb.fileUtils.getStringFromFile("lang/tr.txt"), "\r\n", "\n"),
            i = ft.replaceAll(jsb.fileUtils.getStringFromFile("lang/en.txt"), "\r\n", "\n"),
            a = ft.replaceAll(jsb.fileUtils.getStringFromFile("lang/ja.txt"), "\r\n", "\n"),
            n = ft.replaceAll(jsb.fileUtils.getStringFromFile("lang/ko.txt"), "\r\n", "\n");
        t = t ? t.split("\n") : [], e = e ? e.split("\n") : [], i = i ? i.split("\n") : [], a = a ? a.split("\n") : [], n = n ? n.split("\n") : [];
        var s = "";
        for (var o in t) s += '"' + t[o] + '": ["' + e[o] + '", "' + (i[o] ? i[o] : "") + '", "' + (a[o] ? a[o] : "") + '", "' + (n[o] ? n[o] : "") + '"],\n';
        jsb.fileUtils.writeStringToFile(s, "lang/lang.txt")
    }
}
